version: '3'

services:

  littb:
    build: .
    entrypoint: 'npm-run-all -r -p serve-dist protractor'

    environment:
      - SELENIUM=hub
      # - LITTB_DOCKER_HOST=host.docker.internal
      - LITTB_DOCKER_HOST=littb
    depends_on:
      - chrome

  hub:
    image: selenium/hub
    environment:
      - "JAVA_OPTS=-Dselenium.LOGGER.level=WARNING"

  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
        - HUB_PORT_4444_TCP_ADDR=hub
        - HUB_PORT_4444_TCP_PORT=4444 
        - "JAVA_OPTS=-Dselenium.LOGGER.level=WARNING"
    volumes:
      - /dev/shm:/dev/shm

