window.$ = window.jQuery = require("jquery")
require("lodash")
require("angular")
require("angular-animate")
require("angular-route")
require("angular-touch")
require("angular-ui-bootstrap")
require("angular-spinner")
require("angular-aria")
require("angular-ellipsis")
require("angularjs-slider")
require("angularjs-slider/dist/rzslider.css")
// require("ui-select")
// require("ui-select/dist/select.css")
require("select2/dist/css/select2.css")
require("./lib/select2.js")
require("angular-ui-select2/src/select2.js")
window._.str = require("underscore.string")

// require("components/select2/select2.css")
require("./styles/bootstrap.scss")
require("./styles/styles.scss")

require("./lib/jquery.ui.position.js")
require("./lib/angular-locale_sv-se.js")
require("./lib/FileSaver.js")

require("./scripts/app.js")
require("./scripts/util.js")
require("./scripts/services.js")
require("./scripts/directives.js")
require("./scripts/reading_controller.js")
require("./scripts/search_controller.js")
require("./scripts/library_controller.js")
require("./scripts/dramaweb_controller.js")
require("./scripts/controllers.js")
require("./scripts/lagerlof.js")
require("./scripts/school.js")

// require("./index.html")
// require('file-loader?name=[name].[ext]!./index.html')
