import { expect, test } from "@playwright/test"

const readerPath = "/författare/SöderbergH/titlar/DoktorGlas/sida/-2/etext"
const routes = ["/", "/bibliotek", "/sök", "/epub", "/presentationer", "/om/ide", "/författare/StrindbergA", readerPath]

for (const width of [375, 390, 768]) {
  test(`shared mobile navigation fits all main page types at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 844 })
    for (const route of routes) {
      await page.goto(route)
      await page.locator("[data-site-navigation-ready=true]").waitFor()
      const button = page.locator(".site-menu-toggle")
      const navigation = page.getByRole("navigation", { name: "Huvudnavigation" })
      await expect(button, route).toBeVisible()
      await expect(button).toHaveAttribute("aria-expanded", "false")
      await expect(navigation).toBeHidden()
      const header = page.locator("#leftCorridor")
      const box = await header.boundingBox()
      expect(box!.x, route).toBeGreaterThanOrEqual(-1)
      expect(box!.x + box!.width, route).toBeLessThanOrEqual(width + 1)
      await button.press("Enter")
      await expect(navigation).toBeVisible()
      expect(await navigation.evaluate(element => element.scrollWidth - element.clientWidth), route)
        .toBeLessThanOrEqual(1)
      await expect(button).toHaveAttribute("aria-controls", await navigation.getAttribute("id") ?? "")
      await expect(navigation.getByRole("link", { name: "Biblioteket", exact: true })).toBeVisible()
      await expect(navigation.getByRole("button", { name: "ändra design" })).toHaveCount(0)
      await expect(navigation.locator(".tungsten-grid")).toBeVisible()
      await page.keyboard.press("Tab")
      await expect(navigation.getByRole("combobox", { name: "Snabbsökning" })).toBeFocused()
      await page.keyboard.press("Escape")
      await expect(navigation).toBeHidden()
      await expect(button).toBeFocused()
    }
  })
}

test("mobile navigation closes on outside click and route navigation", async ({ page, isMobile }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/bibliotek")
  await page.locator("[data-site-navigation-ready=true]").waitFor()
  const button = page.locator(".site-menu-toggle")
  const navigation = page.getByRole("navigation", { name: "Huvudnavigation" })
  await button.click()
  if (isMobile) await page.locator("h1").tap()
  else await page.locator("h1").click()
  await expect(navigation).toBeHidden()
  await button.press("Space")
  await navigation.getByRole("link", { name: "Presentationer", exact: true }).click()
  await expect(page).toHaveURL(/\/presentationer$/)
  await expect(navigation).toBeHidden()
  await button.click()
  await navigation.getByRole("link", { name: "Biblioteket", exact: true }).click()
  await expect(page).toHaveURL(/\/bibliotek$/)
  await expect(navigation).toBeHidden()
})

test("quick search remains accessible with the mobile menu closed", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/bibliotek")
  await page.locator("[data-site-navigation-ready=true]").waitFor()
  const button = page.locator(".site-menu-toggle")
  await button.focus()
  await page.keyboard.press("s")
  const dialog = page.getByRole("dialog", { name: "Snabbsökning", exact: true })
  await expect(dialog).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(dialog).toBeHidden()
  await expect(button).toBeFocused()
  await button.click()
  const inlineSearch = page.getByRole("combobox", { name: "Snabbsökning" })
  await expect(inlineSearch).toBeVisible()
  await inlineSearch.focus()
  await expect(dialog).toBeHidden()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("navigation", { name: "Huvudnavigation" })).toBeHidden()
  await expect(button).toBeFocused()
})

test("desktop navigation remains visible after resizing and reader focus hides the header", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/bibliotek")
  await page.locator("[data-site-navigation-ready=true]").waitFor()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await expect(page.getByRole("navigation", { name: "Huvudnavigation" })).toBeVisible()
  await expect(page.locator(".site-menu-toggle")).toBeHidden()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole("navigation", { name: "Huvudnavigation" })).toBeHidden()
  await page.goto(`${readerPath}?fokus`)
  await page.locator("[data-site-navigation-ready=true]").waitFor({ state: "attached" })
  await expect(page.locator("body")).toHaveClass(/reader-focus-mode/)
  await expect(page.locator("#leftCorridor")).toBeHidden()
  await page.keyboard.press("Escape")
  await expect(page.locator(".site-menu-toggle")).toBeVisible()
})
