# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - name: Angular Github Actions
      # uses: mayurrawte/github-angular-actions@latest
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 12.18.3
    # - name: Set up JDK 11
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.11
    - name: Setup environment
      run: |
        yarn global add npm-run-all wait-on
    - name: Main repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        yarn --frozen-lockfile
        npx webdriver-manager update --standalone chrome --versions.chrome=2.46 --gecko false
    - name: Run tests
      run: |
        # npx webdriver-manager start &
        yarn serve-dist &
        npx wait-on http://localhost:9000
        sleep 5
        npx protractor --browser chrome test/e2e/conf_e2e.js
        echo "exited tests with code $?"
